# Generated by Django 3.1.5 on 2021-01-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tahaApp.basemodel')),
                ('related_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahaApp.shop')),
            ],
            bases=('tahaApp.basemodel',),
        ),
    ]
