# Generated by Django 3.1.6 on 2021-02-11 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tahaApp', '0002_auto_20210128_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('woo_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.TextField(blank=True, max_length=1000, null=True)),
                ('alt', models.TextField(blank=True, max_length=1000, null=True)),
                ('original_src', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='woo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='consumer_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='consumer_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='basemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='image',
            field=models.ManyToManyField(to='tahaApp.Image'),
        ),
    ]
