# Generated by Django 3.1.6 on 2021-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0003_auto_20210211_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='shop',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
