# Generated by Django 3.1.6 on 2021-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0005_auto_20210216_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='basemodel',
            name='images',
            field=models.ManyToManyField(to='tahaApp.Image'),
        ),
    ]
