# Generated by Django 3.1.6 on 2021-02-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0006_auto_20210216_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='tahaApp.Image'),
        ),
        migrations.AddField(
            model_name='shop',
            name='images',
            field=models.ManyToManyField(to='tahaApp.Image'),
        ),
    ]
