# Generated by Django 3.1.6 on 2021-02-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0008_auto_20210216_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('d', 'Deactive')], default='d', max_length=2),
        ),
    ]
