# Generated by Django 3.1.6 on 2021-02-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0010_auto_20210216_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='32122', max_length=7),
        ),
    ]
