# Generated by Django 3.1.6 on 2021-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0012_auto_20210217_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='12734', max_length=7),
        ),
    ]
