# Generated by Django 3.1.6 on 2021-02-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahaApp', '0013_auto_20210217_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahaApp.profile'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='message',
            field=models.CharField(default='37903', max_length=7),
        ),
    ]
